### ISSUE TITLE
Kichu Contribute kora jaabe?

### ISSUE THREAD

**Issue by ohbus** [probhakarroy/tcs_humain_challenge#5]
Kono backlogs ache jeta pending which you would like to complete?

Maybe I can help. Maybe not, I'm too noob.

**Comment by probhakarroy** [comment]
collaboration invite send korechi...create a branch and start contributing to this project!

### Some points you need to consider:-

- the dataset TCS provided was really bad in terms of no. of data points so, you might think of using a better dataset that provides for multi-task learning objectives.

- you can think of changing any aspect of the model just let the multi-task learning objective be... like try to incorporate with the multi-prediction head structure, etc.
